Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "zabbix-server"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  ## Masterless salt minion, mount salt local folder.
  config.vm.synced_folder "../salt/", "/srv/salt/"

  ## Use all the defaults:
  config.vm.provision :salt do |salt|

    salt.masterless = true
    salt.minion_config = "salt-minion-local"
    salt.run_highstate = true

  end
end
